channels:
  - numba
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.22
  - scipy>=1.10
  - numba>=0.59.1
  - fftw
  - pyfftw
  - pandas>=0.20.0
  - flake8>=3.7.7
  - flake8-docstrings>=1.5.0
  - black>=22.1.0
  - pytest-cov>=2.10.0
  - jupyterlab>=3.0
  - matplotlib>=3.3.0
  - isort>=5.11.0
