name: Tests
on:
  push:
    branches: '**'
  pull_request:
    branches: main

jobs:
  unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Install xmllint on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install libxml2-utils
        shell: bash
      
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set environment variables
        run:  echo "PYTHON_VERSION=$(curl --location https://devguide.python.org/versions | xmllint --html --xpath '//section[@id="supported-versions"]//table/tbody/tr[count(//section[@id="supported-versions"]//table/tbody/tr[td[.="security"]]/preceding-sibling::*)]/td[1]/p/text()' - 2> /dev/null)" >> $GITHUB_ENV
        shell : bash

      - name: Display Python Version
        run: echo ${{ env.PYTHON_VERSION }}
        shell: bash

      - name: update environment file using python version in macOS
        if: runner.os == 'macOS'
        run: sed -i 's/python.*/python==${{ env.PYTHON_VERSION }}/' environment.yml
        shell: bash

      - name: update environment file using python version NOT in macOS
        if: runner.os != 'macOS'
        run: sed -i 's/python.*/python==${{ env.PYTHON_VERSION }}/' environment.yml
        shell: bash

      - name: display content of environment file
        run: cat environment.yml
        shell: bash
      
      # - name: Set Up Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: ${{ env.PYTHON_VERSION }}
      
      # - name: Display Python Version
      #  run: python -c "import sys; print(sys.version)"
      #  shell: bash
      
      # - name: Upgrade Pip
      #  run: python -m pip install --upgrade pip
      #  shell: bash
      
      # - name: Install requirements
      #  run: python -m pip install --upgrade -r requirements.txt
      #  shell: bash
      
      # - name: Install other dependencies
      #  run: python -m pip install --upgrade pytest coverage black flake8
      #  shell: bash

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          channels: conda-forge
          # mamba-version: "*"
          # channel-priority: true
          # auto-update-conda: true
          auto-activate-base: true
          environment-file: environment.yml
          activate-environment: ""

      - name: Display list of installed packages
        run: conda list
        shell: bash
      
      - name: Show Full Numba Environment
        run: python -m numba -s
        shell: bash
      
      - name: Run Unit Tests
        run: ./test.sh
        shell: bash