name: Tests
on:
  push:
    branches: '**'
  pull_request:
    branches: main
jobs:
  unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
        shell: bash
      - name: Install requirements
        run: python -m pip install --upgrade -r requirements.txt
        shell: bash
      - name: Install other dependencies
        run: python -m pip install --upgrade pytest black flake8
        shell: bash
      - name: Show Full Numba Environment
        run: python -m numba -s
        shell: bash
      - name: Run Unit Tests
        run: source test.sh
        shell: bash